export interface CommandResult {
  success: boolean
  canUndo?: boolean
  canRedo?: boolean
}

abstract class CommandAbstract {
  abstract readonly id: string // autogenerated
  // abstract timestamp: number; // autogenerated
  // abstract exec(): T;
  // abstract undo(): CommandResult;
}

export class Command extends CommandAbstract {
  readonly id: string

  constructor ({ id }: { id: string }) {
    super()
    this.id = id
  }
}
